name: ðŸš€ Deploy website on push
on:
  push:
    branches:
      - rkz-live-test
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: ðŸ“‚ Sync files to marquee-addon-pro test server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.RKZ_FTP_SERVER }}
          username: ${{ secrets.RKZ_FTP_USERNAME }}
          password: ${{ secrets.RKZ_FTP_PASSWORD }}
          server-dir: /marquee-addons-for-elementor/
